project_id = "raozlylupiewgvxhkcgb"

[functions.generate-thumbnail]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.enhance-image]
verify_jwt = true
